### ISSUE TITLE
Responsive Edit Split View screen

### ISSUE THREAD

**Issue by francoisjacquet** [PremiseWP/premise-split-view#3]
![screenshot from 2016-02-11 17 07 09](https://cloud.githubusercontent.com/assets/4723501/12992382/2ade3fcc-d0e2-11e5-8eaa-b546e6e57cdc.png)

The user interface to choose the Split View sides looks usable on small screens, though the separation bar should be adjusted.

**Comment by mvallejo3** [comment]
make the gray line horizontal. reduce padding to 30px top and bottom on gray line.
